import { Router } from "express";

import { posRouter } from "../modules/pos/pos.routes.js";
import { kitchenRouter } from "../modules/kitchen/kitchen.routes.js";
import { roomsRouter } from "../modules/rooms/rooms.routes.js";
import { receptionRouter } from "../modules/reception/reception.routes.js";
import { housekeepingRouter } from "../modules/housekeeping/housekeeping.routes.js";
import { productsRouter } from "../modules/products/products.routes.js";
import { categoriesRouter } from "../modules/categories/categories.routes.js";
import { recipesRouter } from "../modules/recipes/recipes.routes.js";
import { tablesRouter } from "../modules/tables/tables.routes.js";
import { reportsRouter } from "../modules/reports/reports.routes.js";
import { locationsRouter } from "../modules/locations/locations.routes.js";
import { customersRouter } from "../modules/customers/customers.routes.js";
import { serviceCategoriesRouter } from "../modules/service-categories/service-categories.routes.js";
import { unitsOfMeasureRouter } from "../modules/units-of-measure/units-of-measure.routes.js";
import { servicesRouter } from "../modules/services/services.routes.js";
import { paymentMethodsRouter } from "../modules/payment-methods/payment-methods.routes.js";
import { transactionsRouter } from "../modules/transactions/transactions.routes.js";
import { expenseCategoriesRouter } from "../modules/expense-categories/expense-categories.routes.js";
import { expensesRouter } from "../modules/expenses/expenses.routes.js";
import { lostFoundRouter } from "../modules/lost-found/lost-found.routes.js";
import { assetsRouter } from "../modules/assets/assets.routes.js";
import { suppliersRouter } from "../modules/suppliers/suppliers.routes.js";
import { purchasesRouter } from "../modules/purchases/purchases.routes.js";
import { purchaseRequisitionsRouter } from "../modules/purchase-requisitions/purchase-requisitions.routes.js";
import { stockLedgerRouter } from "../modules/stock-ledger/stock-ledger.routes.js";
import { menuRouter } from "../modules/menu/menu.routes.js";
import { employeesRouter } from "../modules/employees/employees.routes.js";
import { departmentsRouter } from "../modules/departments/departments.routes.js";
import { businessProfileRouter } from "../modules/business-profile/business-profile.routes.js";
import { tenantRouter } from "../modules/tenant/tenant.routes.js";
import { rolesRouter } from "../modules/roles/roles.routes.js";
import { authRouter } from "../modules/auth/auth.routes.js";
import { serviceCenterRouter } from "../modules/service-center/service-center.routes.js";

export const router = Router();

router.get("/health", (_req, res) => {
  res.status(200).json({ status: "ok", timestamp: new Date().toISOString() });
});

router.use("/pos", posRouter);
router.use("/kitchen", kitchenRouter);
router.use("/rooms", roomsRouter);
router.use("/reception", receptionRouter);
router.use("/housekeeping", housekeepingRouter);
router.use("/products", productsRouter);
router.use("/categories", categoriesRouter);
router.use("/recipes", recipesRouter);
router.use("/tables", tablesRouter);
router.use("/reports", reportsRouter);
router.use("/locations", locationsRouter);
router.use("/customers", customersRouter);
router.use("/service-categories", serviceCategoriesRouter);
router.use("/units-of-measure", unitsOfMeasureRouter);
router.use("/services", servicesRouter);
router.use("/payment-methods", paymentMethodsRouter);
router.use("/transactions", transactionsRouter);
router.use("/expense-categories", expenseCategoriesRouter);
router.use("/expenses", expensesRouter);
router.use("/lost-found", lostFoundRouter);
router.use("/assets", assetsRouter);
router.use("/suppliers", suppliersRouter);
router.use("/purchases", purchasesRouter);
router.use("/purchase-requisitions", purchaseRequisitionsRouter);
router.use("/stock-ledger", stockLedgerRouter);
router.use("/menu", menuRouter);
router.use("/employees", employeesRouter);
router.use("/departments", departmentsRouter);
router.use("/business-profile", businessProfileRouter);
router.use("/tenant", tenantRouter);
router.use("/roles", rolesRouter);
router.use("/auth", authRouter);
router.use("/service-center", serviceCenterRouter);
