import { Router } from "express";
import { z } from "zod";
import { prisma } from "../../lib/prisma.js";
import { requireModule } from "../../middleware/tenantContext.js";

export const menuRouter = Router();
menuRouter.use(requireModule("POS"));
const categorySchema = z.object({ name: z.string().trim().min(2).max(60), sortOrder: z.coerce.number().int().min(0).default(0) });
const itemSchema = z.object({ categoryId: z.string().cuid(), productId: z.string().cuid().nullable().optional(), name: z.string().trim().min(2).max(120), description: z.string().trim().max(280).nullable().optional(), price: z.coerce.number().positive(), temperature: z.enum(["HOT", "COLD", "OTHER"]).default("OTHER"), isAvailable: z.boolean().default(true) });
const ingredientsSchema = z.object({ ingredients: z.array(z.object({ productId: z.string().cuid(), quantity: z.coerce.number().positive() })).min(1) });
const tenantId = (req: { tenantId?: string }) => { if (!req.tenantId) throw new Error("Tenant context is required"); return req.tenantId; };

menuRouter.get("/categories", async (req, res) => res.json({ categories: await prisma.menuCategory.findMany({ where: { tenantId: tenantId(req) }, include: { items: true }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }) }));
menuRouter.post("/categories", async (req, res) => { const data = categorySchema.safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid category", details: data.error.flatten() }); return; } res.status(201).json({ category: await prisma.menuCategory.create({ data: { tenantId: tenantId(req), ...data.data } }) }); });
menuRouter.patch("/categories/:id", async (req, res) => { const data = categorySchema.partial().safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid category", details: data.error.flatten() }); return; } const updated = await prisma.menuCategory.updateMany({ where: { id: req.params.id, tenantId: tenantId(req) }, data: data.data }); if (!updated.count) { res.status(404).json({ error: "Category not found" }); return; } res.json({ category: await prisma.menuCategory.findUniqueOrThrow({ where: { id: req.params.id } }) }); });
menuRouter.delete("/categories/:id", async (req, res) => { const deleted = await prisma.menuCategory.deleteMany({ where: { id: req.params.id, tenantId: tenantId(req) } }); if (!deleted.count) { res.status(404).json({ error: "Category not found" }); return; } res.status(204).send(); });

menuRouter.get("/items", async (req, res) => res.json({ items: await prisma.menuItem.findMany({ where: { tenantId: tenantId(req) }, include: { category: true, product: true, ingredients: { include: { product: { include: { store: true } } } } }, orderBy: { name: "asc" } }) }));
menuRouter.post("/items", async (req, res) => { const data = itemSchema.safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid menu item", details: data.error.flatten() }); return; } const tid = tenantId(req); const category = await prisma.menuCategory.findFirst({ where: { id: data.data.categoryId, tenantId: tid } }); if (!category) { res.status(400).json({ error: "Choose a category from this property" }); return; } if (data.data.productId && !(await prisma.product.findFirst({ where: { id: data.data.productId, tenantId: tid } }))) { res.status(400).json({ error: "Choose a product from this property" }); return; } const { categoryId, productId, ...item } = data.data; res.status(201).json({ item: await prisma.menuItem.create({ data: { ...item, tenant: { connect: { id: tid } }, category: { connect: { id: categoryId } }, ...(productId ? { product: { connect: { id: productId } } } : {}) }, include: { category: true, product: true } }) }); });
menuRouter.patch("/items/:id", async (req, res) => { const data = itemSchema.partial().safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid menu item", details: data.error.flatten() }); return; } const tid = tenantId(req); const existing = await prisma.menuItem.findFirst({ where: { id: req.params.id, tenantId: tid } }); if (!existing) { res.status(404).json({ error: "Menu item not found" }); return; } const { categoryId, productId, ...item } = data.data; const updated = await prisma.menuItem.update({ where: { id: existing.id }, data: { ...item, ...(categoryId ? { category: { connect: { id: categoryId } } } : {}), ...(productId === null ? { product: { disconnect: true } } : productId ? { product: { connect: { id: productId } } } : {}) }, include: { category: true, product: true } }); res.json({ item: updated }); });
menuRouter.delete("/items/:id", async (req, res) => { const deleted = await prisma.menuItem.deleteMany({ where: { id: req.params.id, tenantId: tenantId(req) } }); if (!deleted.count) { res.status(404).json({ error: "Menu item not found" }); return; } res.status(204).send(); });
menuRouter.get("/items/:id/ingredients", async (req, res) => { const item = await prisma.menuItem.findFirst({ where: { id: req.params.id, tenantId: tenantId(req) }, include: { ingredients: { include: { product: { include: { store: true } } } } } }); if (!item) { res.status(404).json({ error: "Menu item not found" }); return; } res.json({ item, ingredients: item.ingredients }); });
/** Replaces a menu item's recipe. Products remain ingredients, never saleable finished drinks. */
menuRouter.put("/items/:id/ingredients", async (req, res) => { const data = ingredientsSchema.safeParse(req.body); if (!data.success) { res.status(400).json({ error: "Invalid recipe", details: data.error.flatten() }); return; } const tid = tenantId(req); const item = await prisma.menuItem.findFirst({ where: { id: req.params.id, tenantId: tid } }); if (!item) { res.status(404).json({ error: "Menu item not found" }); return; } const ingredientIds = data.data.ingredients.map((ingredient) => ingredient.productId); if (new Set(ingredientIds).size !== ingredientIds.length) { res.status(400).json({ error: "An ingredient can only appear once in a recipe" }); return; } const count = await prisma.product.count({ where: { id: { in: ingredientIds }, tenantId: tid, isActive: true } }); if (count !== ingredientIds.length) { res.status(400).json({ error: "Every ingredient must be an active product from this property" }); return; } const ingredients = await prisma.$transaction(async (tx) => { await tx.menuItemIngredient.deleteMany({ where: { menuItemId: item.id } }); await tx.menuItemIngredient.createMany({ data: data.data.ingredients.map((ingredient) => ({ menuItemId: item.id, ...ingredient })) }); return tx.menuItemIngredient.findMany({ where: { menuItemId: item.id }, include: { product: { include: { store: true } } } }); }); res.json({ ingredients }); });
